package hiber;
// Generated 07-mar-2020 11:29:21 by Hibernate Tools 4.3.1



/**
 * Smartphone generated by hbm2java
 */
public class Smartphone  implements java.io.Serializable {


     private int id;
     private String modelo;
     private Integer bateria;
     private Integer ver;
     private String firmware;

    public Smartphone() {
       this.id = 0;
    }

	
    public Smartphone(int id, String modelo) {
        this.id = id;
        this.modelo = modelo;
    }
    public Smartphone(int id, String modelo, Integer bateria, Integer ver, String firmware) {
       this.id = id;
       this.modelo = modelo;
       this.bateria = bateria;
       this.ver = ver;
       this.firmware = firmware;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Integer getBateria() {
        return this.bateria;
    }
    
    public void setBateria(Integer bateria) {
        this.bateria = bateria;
    }
    public Integer getVer() {
        return this.ver;
    }
    
    public void setVer(Integer ver) {
        this.ver = ver;
    }
    public String getFirmware() {
        return this.firmware;
    }
    
    public void setFirmware(String firmware) {
        this.firmware = firmware;
    }




}


